### ISSUE TITLE
Implement dependency injection

### ISSUE THREAD

**Issue by gaferneira** [gaferneira/meli-react#12]

**Comment by Caxvalencia** [comment]
He escuchado que inversify es una librería buena para hacer inyección de dependencias, o te haces un mini patrón container para hacer eso mismo claro sin tanto estilo pero sirve.

**Comment by gaferneira** [comment]
Implementé al fin inversify y quité mi container que ya no estaba tan escalable.

https://github.com/gaferneira/meli-react/pull/26/files
